### PR TITLE
Bring sync stuff

### PR DESCRIPTION
**Pull request by karlht**
This should bring the 'make build/small/medium/large' stuff over with the config files.

`SERVER_URL` is parameterized as a Make variable and a command-switch to loads-runner.

Simple substitution of self.server_url for the dev server should work ok, I hope.  That's coming next.

### CODE REVIEW

**Comment by m8ttyB** [comment]
This looks good - 2 questions:
- For the large run, how do I test that the `Makefile` kicks off aws instance(s)?
- Is there a different route we want to go for spinning up individual tests? The Makefile has `test_wp.TestWP.test_root_blog` hard-coded as the only test case being executed?

**Comment by karlht** [comment]
We should ptobably write a `test_main` that runs the other tests in various proportions specified in a configuration, e.g. 80% `test_root_blog`, 10% `test_webqa_blog`, 1% `test_comments`, etc.

**Comment by karlht** [comment]
I will also probably set a `THIS_TEST` Make variable, like `SERVER_URL` that defaults to `test_root_blog`, but can  be changed for when we want only one of the individiual tests, e.g. `make THIS_TEST=test_webqa_blog SERVER_URL=https://myblogs.allizom.org medium`

**Comment by m8ttyB** [comment]
Sounds great -- merging

**Pull request merged**
